backend:
  name: github
  repo: BryceMcLeod24/client-repo # Replace per client
  branch: main
media_folder: "static/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }